# Add configuration values here, as shown below.

DROPBOX_KEY: '0xyfkqiid72gz1n'
DROPBOX_SECRET: 'g5bdd19p428ihkd'

DRIVE_KEY: '446929399464-i4b36ug5mhjbs02j27meakgd8sc6ve88.apps.googleusercontent.com'
DRIVE_SECRET: 'lb-4nacGoNmUicTdxbnmd9lu'
