default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: bruse
  password: kex2015

development:
  <<: *default
  database: bruse_development

test:
  <<: *default
  database: bruse_test
